### PR TITLE
Turn on all compiler warnings.

### PR DESCRIPTION
**Pull request by Loki-Astari**
I tuned on all compiler warnings for https://github.com/ArkScript-lang/Ark
    This resulted in some errors in this project.

    This is the fixes required so that it compiles with no warnings.

### CODE REVIEW

**Comment by PierrePharel** [comment]
Hi, can be more specific with kind of errors you caugth

**Comment by Loki-Astari** [comment]
When compiling [Ark](https://github.com/ArkScript-lang/Ark) with full warnings, this repository generates `unused-function` warning.

Note: You have a full function declaration in a header file.

If this header file is included in more than one compilation unit in a project you will have multiple definitions of the function (thus you would be in violation of the multiple definition rule). The only way to get around multiple definition rule is to mark the function as `inline` as required by the standard.

**Comment by PierrePharel** [comment]
ok, I will try to reproduce compilation warning with Ark and review the code (merge your changes), but inline keyword is new for me so I must take a look of that

**Comment by PierrePharel** [comment]
So `inline` made an static function invisible in other translation units but i think we can do it in batter way. But, if I can reproduce and your warnings I will accept your changes and merge it

**Comment by Loki-Astari** [comment]
No quite.

The `inline` is a marker to the linker that a function can be multiple translation units.
Note 1: **Which is required** to make your code valid it if is included from multiple files.

Note 2: Though the function is marked `static` this is pointless in this context (as it is in a header file).
              The term static has no meaning here.


The problem for Ark is that your code is inlined into multiple compilation units.
But not used in each compilation unit. This is marked as a warning.
Currently, I am trying to get Ark to compile with zero compiler warnings (as a compiler warning is a logical error in your thinkging and dangerious).

----

To reproduce the issue.

1: Wait for this [PR](https://github.com/ArkScript-lang/Ark/pull/341) to be merged.
2: [Clone Repository](git@github.com:ArkScript-lang/Ark.git)
3: Remove the line that disables the [warnings](https://github.com/ArkScript-lang/Ark/blob/3fa651b38230295e8fc871304d93a4e299a1945f/CMakeLists.txt#L44) Lines 43-46
4: Build
 * make -Bbuild     -DCMAKE_BUILD_TYPE=Release     -DCMAKE_C_COMPILER=clang     -DCMAKE_CXX_COMPILER=clang++     -DARK_BUILD_EXE=On -DARK_BUILD_MODULES=On -DARK_MOD_ALL=On
 * cmake --build build --config Release

**Pull request merged**
